services:
  grafana:
    user: root
    container_name: 'hda-gitlabcicd-datasource'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
        development: ${DEVELOPMENT:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/hda-gitlabcicd-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/hda-gitlabcicd-datasource
    networks:
      - my-bridge
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.hda-gitlabcicd-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: hda-gitlabcicd-datasource
networks:
  my-bridge:
    external: true
    name: my-bridge
